config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "profiles#show"
  post '/' => "profiles#show"
  post "profiles/search_beer" => "profiles#search_beer", as: :profile_beer_search

  resources :beers do
    resources :reviews
  end

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :users, :through => :reviews

  has_many :reviews
  accepts_nested_attributes_for :reviews

  def self.get_from_api(abv, taste, color)
    json_file = RestClient.get("http://api.brewerydb.com/v2/beers/?format=json&key=#{ENV['BEER_DB_API_KEY']}&withBreweries=Y&abv=#{abv}&srm=#{color}&ibu=#{taste}")  
    JSON.parse(json_file)  
  end


  def self.check_db_for_beer(api_id)
    Beer.where(:api_id => "#{api_id}").blank?
  end

  def self.add_beer_to_db(beer_name, beer_brewery, beer_id, beer_style, beer_abv, beer_srm, beer_ibu, beer_description, beer_labels)
    Beer.create name:beer_name, brewery:beer_brewery, api_id:beer_id,  style:beer_style, abv:beer_abv, srm:beer_srm, ibu:beer_ibu, description:beer_description, label:beer_labels
  end
  
  def self.get_reviews
    if Review.where(:beer_id).blank?
      "Write the first review"
    else
      "Show Review"
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  include ActionView::Helpers::UrlHelper
  belongs_to :beer

  belongs_to :user
  
  def self.get_author(beer_db)
      author_id = Review.find_by(beer_id: "#{beer_db}")["user_id"]
      User.find(author_id)["email"]
  end

  def self.get_body(beer_db)
    Review.find_by(beer_id: "#{beer_db}")["body"]
  end

  def self.find_review(api_id)
    beer_db = Beer.find_by(api_id: "#{api_id}")['id'] 
    if Review.find_by(beer_id: "#{beer_db}")==nil 
      false
    end
  end

  def self.get_current_user_review(api_id, user_id)
    beer_db = Beer.find_by(api_id: "#{api_id}")['id']
    Review.find_by_user_id_and_beer_id("#{user_id}", "#{beer_db}")
  end


  def self.create_review(api_id, user_id)
    beer_db = Beer.find_by(api_id: "#{api_id}")['id']
    if Review.find_by_user_id_and_beer_id("#{user_id}", "#{beer_db}")
      true
    else
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :beers, :through => :reviews

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    @beers = Beer.all
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def new
    @beer = Beer.new
  end

  def create
    @beer = Beer.new(beer_params)

    if @beer.save
      redirect_to @beer
    else
      render :new
    end
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def update
    @beer = Beer.find(params[:id])

    if @beer.update(beer_params)
      redirect_to @beer
    else
      render :edit
    end
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy
    redirect_to root_path, notice: 'Beer deleted'
  end



private

  def beer_params
    params.require(:beer).permit(:reviews_attributes, :name, :brewery, :description, :tags, :thumbnail)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController 

  def show  
  end

  def search_beer
    @beers = Beer.get_from_api(params['beer']['abv'], params['beer']['taste'], params['beer']['color'])['data'].sample(3)
    
    render :show
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
    @beer = Beer.find(params[:beer_id])
  end

  def create
    @review = Review.new(review_params)
    @review.save
    # current_user.reviews << @review
    # current_user.save
    @beer = Beer.find(params[:beer_id])
    @beer.reviews << @review

    if @beer.save
      redirect_to @beer
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to @review
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to root_path, notice: 'Review deleted'
  end

private

  def review_params
    params.require(:review).permit(:user_id, :beer_id, :body, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/_reviews.html.erb
<% if user_signed_in? %>
  <% if Review.create_review(@beer.api_id, current_user.id) %>
    <div class="review">
      Your Review: <%= Review.get_current_user_review(@beer.api_id, current_user.id)["body"] %>
      <% my_review = Review.get_current_user_review(@beer.api_id, current_user.id) %>
      <br>Last Updated: <%=my_review.updated_at %>
    </div>
  <% else %>
      <%= link_to "Add a review for this beer", new_beer_review_path(Beer.find_by(api_id: @beer.api_id)['id']) %> 
      <br>  
  <% end %>
<% else %>
  <%= link_to("Sign in to leave a Review", new_user_session_path) %>
  <br>
<% end %>


<% if @beer.reviews.length > 0 %> 
  <% @beer.reviews.last(5).each do |review| %>
  	<div class="review">
      By: <%= User.find(review.user_id)["first_name"] %>
      <br><%= review.body %>
      <br>Last Updated: <%= review.updated_at %>
    </div>
  <% end %>
<% else %>
  <%= "No Reviews Yet" %>
<% end %>

app/views/beers/show.html.erb
<h2 class='text-center'><%= @beer.name %></h2>
<h3 class='text-center'>By: <%= @beer.brewery %></h2>

<hr>
<br>
<div id="beer_info">

  <% label = @beer.label %>

  <% if label == nil %>
    <%= image_tag("no-label.png", width:"150", height:"150") %> 
  <% else %>
    <%= image_tag(label, width:"150", height:"150") %> 
  <% end %>


  	<h4>Description:</h4>
  	<p><%= @beer.description %></p>
    <hr>
    
    <div class="stats col-md-4">
      <h4>Stats:</h4>
      Style: <%= @beer.style %><br>
      ABV: <%= @beer.abv %><br>
      SRM: <%= @beer.srm %><br>
      IBU: <%= @beer.ibu %>
    </div>

    <div class="beer_reviews col-md-8">
    	<h4>Reviews:</h4>
      <%= render 'reviews' %> 
    </div>      

    <div class="col-md-12">
      <%= link_to 'Try a New Search', root_path, id:"btn-home", class:"btn btn-primary " %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brew Q?</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://bootswatch.com/spacelab/bootstrap.css">
  <link href='https://fonts.googleapis.com/css?family=Yellowtail' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<div id="log_out">
			<% if user_signed_in? %>
				<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to 'Log in to leave Notes', new_user_session_path %>
			<% end %>
		</div>
		<div id="logo"><%= link_to 'Brew Q?', root_path %></div>
	</div>
	

	<%= alert %>

	<div class="container">
    	<%= yield %>
    	<div id="footer" class="col-md-12">
	    	<%= link_to image_tag("Powered-By-BreweryDB_banner.png", width:"250", height:"63"), "http://www.brewerydb.com/" %>
	    	<span style="float:right">Site created by Patrick Mattei -- <a href="http://patrickmattei.com">patrickmattei.com</a></p>
		</div>
	</div>
</body>
</html>

app/views/profiles/_found.html.erb
<% @beers.each do |beer| %>
	<div id="found_beer" class="col-md-4">
		<% api_id = beer['id'] %>
		<% beer_name = beer['name']  %>
		<% beer_brewery = beer['breweries'][0]['name'] %>
		<% beer_style = beer['style']['name'] %>
		<% beer_abv = beer['abv'] %>
		<% beer_srm = beer['srmId'] %>
		<% beer_ibu = beer['ibu'] %>
		<% beer_description = beer['description'] %>

		<% if beer['labels'] %>		
			<% beer_labels = beer['labels']['large'].to_s %>
		<% else %>
			<% beer_labels = "no-label.png" %>
		<% end %>
			
		<% if Beer.check_db_for_beer(api_id) %>
			<% Beer.add_beer_to_db(beer_name, beer_brewery, api_id, beer_style, beer_abv, beer_srm, beer_ibu, beer_description, beer_labels) %>
		<% end %>


		<div id="found_beer_info">
			<%= link_to "../beers/#{Beer.find_by(api_id: "#{api_id}")['id']}" do %>
				<div id="found_beer_info">
					<%= image_tag("#{beer_labels}", width:"150", height:"150") %><br>
					NAME: <%= beer_name %><br>
					BREWERY: <%= beer_brewery %><br>
					STYLE: <%= beer_style %><br>
					ABV: <%= beer_abv%><br>
					SRM: <%= beer_srm %><br>
					IBU: <%= beer_ibu %><br>
					DESCRIPTION: <%= truncate(beer_description, length: 120) %><br>
				</div>
			<% end %>
			
			<% beer_db = Beer.find_by(api_id: "#{api_id}")['id'] %>


			Recent Reviews:
			<div class="found_reviews">
				<% if Review.find_review(api_id)==false %>
					<%= "No Reviews" %>
				<% else %>
					<%= "Author: #{Review.get_author(beer_db)}" %><br>
					<%= "Review: #{truncate(Review.get_body(beer_db), length: 120)}" %>					
				<% end %>
			</div>

			<% if user_signed_in? %>
				<% if Review.create_review(api_id, current_user.id) %>
		  			<%= "Your Review: #{truncate(Review.get_current_user_review(api_id, current_user.id)["body"], length: 100)}" %>
	    		<% else %>
	       			<%= link_to "Add a review for this beer", new_beer_review_path(Beer.find_by(api_id: "#{api_id}")['id']) %>   
	       		<% end %>
	       	<% else %>
	       		<%= "Sign in to leave a review" %>
	       	<% end %>
		</div>
	</div>
<% end %>

app/views/profiles/_recent_reviews.erb
<h3>Recent Reviews</h3>
<% if Review.all.length > 0 %>
	<% Review.last(3).each do |review| %>
		<% beer_id = review["beer_id"] %>
		<% author_id = review["user_id"] %>
		
		<%= link_to("/beers/#{beer_id}") do %>
			<div class="recent_review">
				<div class="recent_review_image">
					<%= image_tag("#{Beer.find(review.beer_id)["label"]}", width:"150", height:"150") %>
				</div>
				<h4 class="list-group-item-heading">
					<%= Beer.find(review.beer_id)["name"] %>
				</h4>
				<div class="recent_review_author">
					By: <%= User.find(author_id)["first_name"] %>
				</div>
				<div class="recent_review_body">
					<%= truncate(review["body"], length: 120) %>
				</div>
			</div>
		<% end %>
	<% end %>
<% else %>
	<%= "No Reviews in the System" %>
<% end %>

app/views/profiles/_search.html.erb
<%= simple_form_for :beer, url: profile_beer_search_path do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs" style="width: 40%">
    <%= f.input  :color,  required: true, collection: [["Light", "1,20"], ["Dark", "20,40"]], label: "I want a beer that's:" %>
    <%= f.input  :taste,   collection: [["Sweet", "0,50"], ["Sour", "50,100"]], label: "And tastes:" %>
    <%= f.input  :abv,  collection: [["0-4.9%","0,4.9"], ["5.0%-7.9%", "5.0,7.9"], ["8.0%-10.9%", "8.0,10.9"], ["11.0%-PARTY TIME", "11,100"]], label: "With an ABV (Alcohol By Volume) of:" %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit, "Search", class: 'btn btn-primary', id: 'search_beer' %>
  </div>
<% end %>

app/views/profiles/_user_reviews.html.erb
<% if user_signed_in? %> 
	<div id="profile_reviews">
		<h3>Your Recent Reviews</h3>
		<div class="list-group">
			<% current_user.reviews.last(5).each do |review| %>
				<% beer_id = review["beer_id"] %>
				<%= link_to("/beers/#{beer_id}") do %>
					<div class="list-group-item">
						<h4 class="list-group-item-heading">
							Name: <%= Beer.find(review.beer_id)["name"] %>
						</h4>
						<div class="list-group-item-text">
							<%= truncate(review.body, length:500) %>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/profiles/show.html.erb
<div id="profile_header">
	<div id ="profile_information">
		<% if user_signed_in? %> 
			<%= "You are logged in as #{current_user.email}" %>
			<br>
			<%= "Hi, #{current_user.first_name}" %>
		<% end %>
	</div>

	<h2>What are you in the mood for?</h2><br>
</div>

<div id="main">
	<div id ="recent_reviews">
		<%= render 'recent_reviews' unless @beers %>
	</div>


	<div id="search">
		<%= render 'search' unless @beers %>

		<% if @beers %>
		  <%= render 'found' %>
		<% end %>
	</div>

	<%= render 'user_reviews' unless @beers %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for @review,  :url => url_for(:controller => 'reviews', :action => 'create') do |f| %>
	<div class="input-group">
		<%= f.input  :body %>
	</div>
	<br>
	<%= f.hidden_field :beer, :value => @beer.id %>
	<%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
	<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form' %>